version: '3.7'
services:
  telegraf:
    image: telegraf:latest
    command: ["telegraf", "--config", "/telegraf.conf"]
    volumes:
      - "/:/hostfs:ro"
      - "/root/telegraf.conf:/telegraf.conf"
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_PROC=/hostfs/proc
  wavefront-proxy:
    image: wavefronthq/proxy:latest
    environment:
      - WAVEFRONT_URL=https://nimba.wavefront.com/api/
      - WAVEFRONT_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - JAVA_HEAP_USAGE=512m
    ports:
      - "2878:2878"
      - "4242:4242"
